<?php
/**
 * faculty/face_verification.php
 * Verifies a live face against the one-time face template captured during registration.
 * This page never replaces the stored biometric template.
 */
require_once __DIR__ . '/../db.php';
session_start();
requireLogin('faculty');

$pageTitle = 'Face Verification';
$facultyId = (int)$_SESSION['user_id'];
$faculty   = getFacultyOnboarding($conn, $facultyId);
if (!$faculty) redirect('/logout.php');

$mode = $_GET['mode'] ?? $_POST['mode'] ?? 'verify';
$isLoginFace = ($mode === 'login');

if ($isLoginFace && (int)($_SESSION['pending_face_user_id'] ?? 0) !== $facultyId) {
    redirect('/faculty/dashboard.php');
}

if (!$isLoginFace && ($faculty['account_status'] ?? 'Active') !== 'Pending Face Verification') {
    redirect('/faculty/dashboard.php');
}

$errors = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $dataUrl = $_POST['face_image'] ?? '';
    $descriptorJson = $_POST['face_descriptor'] ?? '';

    // Validate the live face descriptor generated by the browser.
    $descriptor = null;
    if (!empty($descriptorJson)) {
        $decoded = json_decode($descriptorJson, true);
        if (is_array($decoded) && count($decoded) === 128) {
            $descriptor = array_map('floatval', $decoded);
        }
    }
    if ($descriptor === null) {
        $errors[] = 'Face descriptor could not be generated. Please ensure good lighting and try again.';
    }

    // Verify live face against the permanent template captured during registration.
    if (empty($errors)) {
        $stored = json_decode($faculty['face_descriptor'] ?? '', true);
        if (!is_array($stored) || count($stored) !== 128) {
            $errors[] = 'No registered face template found. Please contact the administrator.';
        } else {
            $distance = faceDescriptorDistance(array_map('floatval', $stored), $descriptor);
            if ($distance > 0.55) {
                $errors[] = 'The detected face does not match the registered faculty account. Please use the registered face associated with this account.';
                logActivity($conn, 'EMAIL_OTP_FAILED', "Face verification failed for {$faculty['name']} ({$faculty['email']}); distance={$distance}");
            }
        }
    }

    // Optional audit snapshot only; never replace users.face_descriptor here.
    if (empty($errors) && preg_match('/^data:image\/jpeg;base64,/', $dataUrl)) {
        $uploadDir = dirname(__DIR__) . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'faces';
        if (!is_dir($uploadDir)) mkdir($uploadDir, 0775, true);
        $imageData = base64_decode(substr($dataUrl, strpos($dataUrl, ',') + 1), true);
        if ($imageData !== false) {
            file_put_contents($uploadDir . DIRECTORY_SEPARATOR . "faculty_{$facultyId}_verify.jpg", $imageData);
        }
    }

    if (empty($errors)) {
        logActivity($conn, 'FACE_VERIFIED', "Face verification completed for {$faculty['name']}");

        if ($isLoginFace) {
            if (tableExists($conn, 'email_otps')) {
                $otp = generateOtp($conn, $facultyId, 'login_otp');
                if (!sendOtpEmail($faculty['email'], $faculty['name'], $otp)) {
                    logActivity($conn, 'EMAIL_SEND_FAILED', "Login OTP email FAILED after face verification for {$faculty['email']}: " . getLastMailError());
                    setFlash('danger', 'Unable to send email. [DEBUG] ' . getLastMailError());
                    redirect('/faculty/face_verification.php?mode=login');
                }
                logActivity($conn, 'EMAIL_OTP_SENT', "Login OTP sent to {$faculty['email']} after face verification");
            }
            unset($_SESSION['pending_face_user_id']);
            $_SESSION['pending_otp_user_id'] = $facultyId;
            redirect('/faculty/email_otp.php?mode=login');
        }

        $verifyFields = [];
        if (columnExists($conn, 'users', 'face_verified')) $verifyFields[] = 'face_verified = 1';
        if (columnExists($conn, 'users', 'face_verified_at')) $verifyFields[] = 'face_verified_at = NOW()';
        if ($verifyFields) {
            $fvUpd = $conn->prepare("UPDATE users SET " . implode(', ', $verifyFields) . " WHERE id = ?");
            if ($fvUpd) { $fvUpd->bind_param('i', $facultyId); $fvUpd->execute(); $fvUpd->close(); }
        }
        if (columnExists($conn, 'users', 'account_status')) {
            $stUpd = $conn->prepare("UPDATE users SET account_status = 'Pending Email Verification' WHERE id = ?");
            if ($stUpd) { $stUpd->bind_param('i', $facultyId); $stUpd->execute(); $stUpd->close(); }
        }

        if (tableExists($conn, 'email_otps')) {
            $otp = generateOtp($conn, $facultyId, 'email_verification');
            if (!sendOtpEmail($faculty['email'], $faculty['name'], $otp)) {
                logActivity($conn, 'EMAIL_SEND_FAILED', "OTP email FAILED after face verification for {$faculty['email']}: " . getLastMailError());
                if (columnExists($conn, 'users', 'account_status')) {
                    $rollback = $conn->prepare("UPDATE users SET account_status = 'Pending Face Verification' WHERE id = ?");
                    if ($rollback) { $rollback->bind_param('i', $facultyId); $rollback->execute(); $rollback->close(); }
                }
                setFlash('danger', 'Unable to send email. [DEBUG] ' . getLastMailError());
                redirect('/faculty/face_verification.php');
            }
            logActivity($conn, 'EMAIL_OTP_SENT', "OTP sent to {$faculty['email']} after face verification");
        }

        pushNotification($conn, 'Face Verification Completed',
            "{$faculty['name']} completed face verification. Awaiting email OTP.",
            'success', '/admin/faculty/index.php');

        setFlash('info', 'Face verified! A 6-digit code has been sent to your registered email.');
        redirect('/faculty/email_otp.php');
    }
}
include __DIR__ . '/../authentication.php';
?>

<style>
.camera-wrap {
  position: relative; background: #111; border-radius: 12px;
  overflow: hidden; aspect-ratio: 4/3; max-height: 340px;
}
.camera-wrap video { width: 100%; height: 100%; object-fit: cover; display: block; }
.face-guide {
  position: absolute; inset: 12% 22%; border: 3px solid rgba(255,255,255,.95);
  border-radius: 50%; box-shadow: 0 0 0 999px rgba(0,0,0,.28); pointer-events: none;
  transition: border-color .3s;
}
.face-guide.stable { border-color: #198754; box-shadow: 0 0 0 999px rgba(0,0,0,.28), 0 0 0 4px #198754; }
.scan-line {
  position: absolute; left: 18%; right: 18%; height: 2px; top: 16%;
  background: #0d6efd; animation: scan 1.8s linear infinite; opacity: .85;
}
@keyframes scan { 0%{top:16%} 50%{top:82%} 100%{top:16%} }
.face-tick {
  position: absolute; inset: 0; display: flex; align-items: center;
  justify-content: center; pointer-events: none;
}
.progress-ring {
  position: absolute; top: 50%; left: 50%; transform: translate(-50%,-50%);
  pointer-events: none;
}
</style>

<div class="row justify-content-center">
  <div class="col-xl-7 col-lg-9">
    <div class="d-flex justify-content-between align-items-start mb-3 flex-wrap gap-2">
      <div>
        <h5 class="mb-0 fw-bold"><i class="bi bi-person-bounding-box text-primary me-2"></i>Face Verification</h5>
        <div class="text-muted small">Position your face inside the guide and hold still for 1–2 seconds. Capture is automatic.</div>
      </div>
      <span class="badge bg-warning text-dark">Step 1 of 2</span>
    </div>

    <?php if ($errors): ?>
    <div class="alert alert-danger">
      <strong><i class="bi bi-exclamation-triangle-fill me-1"></i>Verification Failed</strong>
      <ul class="mb-0 ps-3 mt-1"><?php foreach ($errors as $e) echo '<li>' . htmlspecialchars($e) . '</li>'; ?></ul>
    </div>
    <?php endif; ?>

    <form method="POST" id="faceForm">
      <input type="hidden" name="mode" value="<?= htmlspecialchars($mode) ?>">
      <input type="hidden" name="face_image"      id="face_image">
      <input type="hidden" name="face_descriptor" id="face_descriptor">

      <div class="card">
        <div class="card-body">
          <div class="camera-wrap mb-3" id="cameraWrap">
            <video id="video" autoplay playsinline webkit-playsinline muted></video>
            <div class="face-guide" id="faceGuide"></div>
            <div class="scan-line"  id="scanLine"></div>
            <div class="face-tick d-none" id="faceTick">
              <i class="bi bi-check-circle-fill text-success" style="font-size:3.5rem;filter:drop-shadow(0 2px 8px rgba(0,0,0,.6))"></i>
            </div>
          </div>

          <!-- Status bar -->
          <div class="alert mb-0 d-flex align-items-center gap-2" id="statusBox" role="alert">
            <div class="spinner-border spinner-border-sm flex-shrink-0" id="statusSpinner"></div>
            <span id="statusText">Opening camera and loading face detector…</span>
          </div>

          <!-- Progress bar (shown during stable countdown) -->
          <div class="progress mt-2 d-none" style="height:6px;" id="progressWrap">
            <div class="progress-bar bg-success progress-bar-striped progress-bar-animated"
                 id="progressBar" style="width:0%"></div>
          </div>

          <div class="d-grid mt-2 d-none" id="retryCameraWrap">
            <button type="button" class="btn btn-outline-secondary btn-sm" id="retryCameraBtn">
              <i class="bi bi-arrow-clockwise me-1"></i>Retry Camera
            </button>
          </div>
        </div>
      </div>
    </form>

    <div class="card mt-3 border-0 bg-light">
      <div class="card-body py-2 small text-muted">
        <i class="bi bi-lightbulb me-1 text-warning"></i>
        <strong>Tips:</strong> Ensure good lighting on your face. Look directly at the camera. 
        Remove glasses if detection fails. Only one face should be in frame.
      </div>
    </div>
  </div>
</div>

</div></div><!-- close main content from authentication.php -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

<!-- MediaPipe for fast bounding-box detection -->
<script src="https://cdn.jsdelivr.net/npm/@mediapipe/face_detection/face_detection.js"></script>
<!-- face-api.js for 128-D descriptor -->
<script src="https://cdn.jsdelivr.net/npm/face-api.js@0.22.2/dist/face-api.min.js"></script>
<!-- Shared robust camera bootstrap (getUserMedia + retry + browser compatibility) -->
<script src="/assets/face-camera.js"></script>

<script>
/* ── Elements ─────────────────────────────────────────────────────────────── */
const video       = document.getElementById('video');
const faceGuide   = document.getElementById('faceGuide');
const scanLine    = document.getElementById('scanLine');
const faceTick    = document.getElementById('faceTick');
const statusBox   = document.getElementById('statusBox');
const statusText  = document.getElementById('statusText');
const statusSpinn = document.getElementById('statusSpinner');
const progressWrap= document.getElementById('progressWrap');
const progressBar = document.getElementById('progressBar');
const retryWrap   = document.getElementById('retryCameraWrap');
const retryBtn    = document.getElementById('retryCameraBtn');

/* ── State ────────────────────────────────────────────────────────────────── */
// Time-based hold detection: capture after the face has been continuously
// well-positioned for HOLD_DURATION_MS, regardless of how many detection
// callbacks fire in that window. This replaces a frame-count approach
// (accumulate N `onResults` calls) that assumed a steady ~8 callbacks/sec.
// On many mobile devices (and some desktop browsers under load) MediaPipe's
// `send()` → `onResults()` round trip does not keep up with that rate — a
// single detection pass can take anywhere from ~50ms to 500ms+ depending on
// the device — so the frame count advanced far slower than real time, and a
// single slow/late callback (or one frame the model was mid-processing when
// the head moved a few millimeters) reset the counter to 0 and forced the
// full sequence to start over. On slower phones this could effectively
// never finish, which is exactly the "stuck on Hold still…" symptom.
const HOLD_DURATION_MS = 1700; // ~1.7s of continuous good detection required
const MIN_BRIGHTNESS = 45; // 0-255 luma; below this ask for more light
let holdStartTime    = null; // timestamp (ms) when the current unbroken good-detection streak began; null = not currently holding
let detectionBusy    = false; // true while a faceDetection.send() call is in flight
let submitted        = false;
let faceApiReady     = false;
let cameraHandle     = null;

/* ── Status helper ───────────────────────────────────────────────────────── */
function setStatus(msg, type = 'info', spin = true) {
  statusBox.className = `alert mb-0 d-flex align-items-center gap-2 alert-${type}`;
  statusText.textContent = msg;
  statusSpinn.style.display = spin ? '' : 'none';
}

/* ── Model loading with sessionStorage caching ───────────────────────────── */
const MODEL_URL = 'https://cdn.jsdelivr.net/npm/@vladmandic/face-api/model';

async function loadFaceApiModels() {
  try {
    await Promise.all([
      faceapi.nets.tinyFaceDetector.loadFromUri(MODEL_URL),
      faceapi.nets.faceLandmark68TinyNet.loadFromUri(MODEL_URL),
      faceapi.nets.faceRecognitionNet.loadFromUri(MODEL_URL),
    ]);
    faceApiReady = true;
    console.log('face-api.js models loaded');
  } catch (e) {
    console.warn('face-api.js models could not load:', e);
  }
}

/* ── Generate 128-D descriptor ───────────────────────────────────────────── */
async function generateDescriptor() {
  if (!faceApiReady) return null;
  try {
    const det = await faceapi
      .detectSingleFace(video, new faceapi.TinyFaceDetectorOptions({ scoreThreshold: 0.45 }))
      .withFaceLandmarks(true)   // tiny landmarks model
      .withFaceDescriptor();
    return det ? det.descriptor : null;
  } catch (e) {
    console.warn('descriptor error:', e);
    return null;
  }
}

/* ── Capture + submit ────────────────────────────────────────────────────── */
async function captureAndSubmit() {
  if (submitted) return;
  submitted = true;

  // Hide scan line; show tick
  scanLine.style.display = 'none';
  faceTick.classList.remove('d-none');
  faceGuide.classList.add('stable');
  progressWrap.classList.add('d-none');

  setStatus('🔵 Verifying Face... Please stay still.', 'primary', true);

  // Capture JPEG
  const cvs = document.createElement('canvas');
  cvs.width  = video.videoWidth  || 640;
  cvs.height = video.videoHeight || 480;
  cvs.getContext('2d').drawImage(video, 0, 0, cvs.width, cvs.height);
  document.getElementById('face_image').value = cvs.toDataURL('image/jpeg', 0.88);

  // Generate descriptor (fast — already warmed up). Retry automatically a
  // couple of times before giving up — slower mobile devices sometimes miss
  // the first pass while the model is still warming up on this exact frame.
  let desc = await generateDescriptor();
  if (!desc) { await new Promise(r => setTimeout(r, 250)); desc = await generateDescriptor(); }
  if (!desc) { await new Promise(r => setTimeout(r, 400)); desc = await generateDescriptor(); }
  if (desc && desc.length === 128) {
    document.getElementById('face_descriptor').value = JSON.stringify(Array.from(desc));
    setStatus('🔵 Face captured! Submitting verification…', 'success', true);
  } else {
    submitted = false;
    holdStartTime = null;
    faceTick.classList.add('d-none');
    scanLine.style.display = '';
    faceGuide.classList.remove('stable');
    setStatus('🔴 Face recognition data could not be generated. Please check your connection, improve lighting, and try again.', 'danger', false);
    return;
  }

  document.getElementById('faceForm').submit();
}

/* ── Bounding-box helper ─────────────────────────────────────────────────── */
function getBox(det) {
  const b = det.boundingBox || det.locationData?.relativeBoundingBox;
  if (!b) return null;
  return {
    xCenter: b.xCenter ?? (b.xMin  + b.width  / 2),
    yCenter: b.yCenter ?? (b.yMin  + b.height / 2),
    width:   b.width,
    height:  b.height,
  };
}

/* ── Hold-timer reset helper ──────────────────────────────────────────────
 * Per the fix requirements, the hold timer should ONLY be cleared when the
 * face truly disappears, multiple faces appear, the face leaves the guide,
 * or the face becomes too small/too large — never for small natural head
 * movements while still inside the guide, and never merely for a brief dip
 * in lighting (that just pauses the on-screen progress, see below).
 */
function resetHold() {
  holdStartTime = null;
  progressWrap.classList.add('d-none');
  progressBar.style.width = '0%';
  faceGuide.classList.remove('stable');
}

/* ── MediaPipe setup ─────────────────────────────────────────────────────── */
const faceDetection = new FaceDetection({
  locateFile: f => `https://cdn.jsdelivr.net/npm/@mediapipe/face_detection/${f}`
});
faceDetection.setOptions({ model: 'short', minDetectionConfidence: 0.65 });

faceDetection.onResults(results => {
  if (submitted) return;
  const faces = results.detections || [];

  if (faces.length === 0) {
    resetHold();
    setStatus('🟡 No face detected. Please position your face inside the guide.', 'info');
    return;
  }
  if (faces.length > 1) {
    resetHold();
    setStatus('🔴 Multiple faces detected. Please ensure only one person is visible.', 'danger');
    return;
  }

  const box = getBox(faces[0]);
  const tooSmall = box && box.width > 0 && box.width < 0.16;
  const tooLarge = box && box.width > 0.85;
  const centered = box
    && box.xCenter > 0.32 && box.xCenter < 0.68
    && box.yCenter > 0.25 && box.yCenter < 0.75
    && box.width   > 0.16;

  if (tooSmall) {
    resetHold();
    setStatus('🟡 Move closer to the camera.', 'warning');
    return;
  }
  if (tooLarge) {
    resetHold();
    setStatus('🟡 Move back a little — you are too close to the camera.', 'warning');
    return;
  }
  if (!centered) {
    resetHold();
    setStatus('🟡 Center your face inside the guide.', 'warning');
    return;
  }

  const brightness = FaceCamera.estimateBrightness(video);
  if (brightness < MIN_BRIGHTNESS) {
    // Position/size are still fine — this is intentionally NOT one of the
    // reset conditions. A passing shadow or brief glare shouldn't throw away
    // an otherwise-good hold streak; just pause the visible progress until
    // brightness recovers, then continue counting from where it left off.
    progressWrap.classList.add('d-none');
    faceGuide.classList.remove('stable');
    setStatus('🟡 Lighting is too dark. Please improve the lighting.', 'warning');
    return;
  }

  // Face is present, alone, centered, correctly sized, and well lit.
  const now = performance.now();
  if (holdStartTime === null) holdStartTime = now;
  const elapsed = now - holdStartTime;
  const pct = Math.min(100, Math.round((elapsed / HOLD_DURATION_MS) * 100));
  progressWrap.classList.remove('d-none');
  progressBar.style.width = pct + '%';

  if (elapsed >= HOLD_DURATION_MS) {
    captureAndSubmit();
  } else {
    faceGuide.classList.add('stable');
    setStatus('🟢 Face detected. Hold still…', 'success');
  }
});

/* ── Camera + model bootstrap ─────────────────────────────────────────────
 * Uses the shared FaceCamera.start() helper (assets/face-camera.js) instead
 * of the MediaPipe `Camera` utility: it requests getUserMedia directly with
 * a graded fallback of constraints, waits for real decodable video
 * dimensions before starting detection (fixes the black "Camera Ready"
 * preview seen on some Android/Samsung Internet builds), and reports
 * specific, actionable messages for permission-denied / no-camera / camera-
 * in-use / insecure-context failures instead of a single generic error.
 */
async function startCamera() {
  retryWrap.classList.add('d-none');
  setStatus('Requesting camera access…', 'info', true);
  try {
    cameraHandle = await FaceCamera.start(video, {
      fps: 8,
      // Guard against overlapping detection passes: on slower phones a
      // single faceDetection.send() → onResults() round trip can take
      // longer than the ~125ms frame interval above. Without this guard the
      // rAF-driven onFrame() below keeps firing and queues up more send()
      // calls than the model can actually process, which causes onResults
      // to arrive late, out of order, or in bursts — making frame-counted
      // "stability" wildly inconsistent on exactly this kind of device.
      // Waiting for the previous call to finish keeps at most one detection
      // in flight at any time, regardless of device speed.
      onFrame: () => {
        if (submitted || detectionBusy) return;
        detectionBusy = true;
        Promise.resolve(faceDetection.send({ image: video }))
          .catch(e => console.warn('face detection send error:', e))
          .finally(() => { detectionBusy = false; });
      },
      onRetryNotice: (msg) => setStatus(msg, 'warning', true),
    });
    if (faceApiReady) {
      setStatus('Camera ready. Position your face in the oval guide.', 'info');
    } else {
      setStatus('Camera ready. Loading face recognition model…', 'info', true);
    }
  } catch (e) {
    console.warn('Camera start failed:', e);
    setStatus(e.friendlyMessage || FaceCamera.describeCameraError(e), 'danger', false);
    // iOS Safari caches a permission denial for the page session — a JS
    // retry will just fail again silently. A full reload (after the user
    // fixes the setting) is the only thing that re-prompts there.
    const needsReload = (e && (e.name === 'NotAllowedError' || e.name === 'PermissionDeniedError')) && FaceCamera.isIOS();
    retryBtn.innerHTML = needsReload
      ? '<i class="bi bi-arrow-clockwise me-1"></i>Reload Page'
      : '<i class="bi bi-arrow-clockwise me-1"></i>Retry Camera';
    retryBtn.dataset.reload = needsReload ? '1' : '0';
    retryWrap.classList.remove('d-none');
  }
}

retryBtn?.addEventListener('click', () => {
  if (retryBtn.dataset.reload === '1') { window.location.reload(); return; }
  if (cameraHandle) { cameraHandle.stop(); cameraHandle = null; }
  submitted = false; holdStartTime = null; detectionBusy = false;
  startCamera();
});

setStatus('Loading face detection models…', 'info', true);

loadFaceApiModels()
  .then(() => { if (cameraHandle) setStatus('Camera ready. Position your face in the oval guide.', 'info'); })
  .catch(() => setStatus('Face recognition model did not load. Please refresh the page and try again.', 'danger', false));

startCamera();

window.addEventListener('beforeunload', () => { if (cameraHandle) cameraHandle.stop(); });

/* ── Sidebar toggle ──────────────────────────────────────────────────────── */
function toggleSidebar(){document.getElementById('sidebar').classList.toggle('show');document.getElementById('sidebarOverlay').classList.toggle('show');}
function closeSidebar(){document.getElementById('sidebar').classList.remove('show');document.getElementById('sidebarOverlay').classList.remove('show');}
</script>
</body></html>
